#include "quantum.h"

#ifdef ENCODER_MAP_ENABLE

const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(KC_PGDN, KC_PGUP) },
    [1] = { ENCODER_CCW_CW(KC_TRANSPARENT, KC_TRANSPARENT), ENCODER_CCW_CW(KC_TRANSPARENT, KC_TRANSPARENT) },
    [2] = { ENCODER_CCW_CW(KC_TRANSPARENT, KC_TRANSPARENT), ENCODER_CCW_CW(KC_TRANSPARENT, KC_TRANSPARENT) },
    [3] = { ENCODER_CCW_CW(KC_TRANSPARENT, KC_TRANSPARENT), ENCODER_CCW_CW(KC_TRANSPARENT, KC_TRANSPARENT) },
};

#endif